# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-01 18:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zerver', '0081_make_emoji_lowercase'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='enable_persistent_desktop_notifications',
            field=models.BooleanField(default=True),
        ),
    ]
