# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-27 13:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zerver', '0082_userprofile_enable_persistent_desktop_notifications'),
        ('zerver', '0112_index_muted_topics'),
    ]

    operations = [
    ]
