# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-27 15:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('zerver', '0113_merge_20180327_1331'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='mute_notifications_until',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
    ]
