# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-19 12:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zerver', '0155_change_default_realm_description'),
        ('zerver', '0114_userprofile_mute_notifications_until'),
    ]

    operations = [
    ]
